export const APP_CONFIG = {
  DEFAULT_LANGUAGE: "es",
  SUPPORTED_LANGUAGES: ["es", "en"] as const,
  DEFAULT_CURRENCY: "COP",
  INCUBATION_DAYS: 80,
  SYNC_INTERVAL_MS: 30_000,
  NEONATO_SIZE_INCHES: 9,
} as const;
