export const COUNTRIES = [
  { code: "AR", name: "Argentina" },
  { code: "BO", name: "Bolivia" },
  { code: "BR", name: "Brasil" },
  { code: "CL", name: "Chile" },
  { code: "CO", name: "Colombia" },
  { code: "CR", name: "Costa Rica" },
  { code: "CU", name: "Cuba" },
  { code: "DO", name: "República Dominicana" },
  { code: "EC", name: "Ecuador" },
  { code: "SV", name: "El Salvador" },
  { code: "GT", name: "Guatemala" },
  { code: "HN", name: "Honduras" },
  { code: "MX", name: "México" },
  { code: "NI", name: "Nicaragua" },
  { code: "PA", name: "Panamá" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Perú" },
  { code: "UY", name: "Uruguay" },
  { code: "VE", name: "Venezuela" },
  { code: "US", name: "Estados Unidos" },
  { code: "AU", name: "Australia" },
  { code: "ZA", name: "Sudáfrica" },
] as const;

export const CURRENCIES = [
  { code: "ARS", name: "Peso Argentino (ARS)" },
  { code: "BOB", name: "Boliviano (BOB)" },
  { code: "BRL", name: "Real Brasileño (BRL)" },
  { code: "CLP", name: "Peso Chileno (CLP)" },
  { code: "COP", name: "Peso Colombiano (COP)" },
  { code: "CRC", name: "Colón Costarricense (CRC)" },
  { code: "CUP", name: "Peso Cubano (CUP)" },
  { code: "DOP", name: "Peso Dominicano (DOP)" },
  { code: "GTQ", name: "Quetzal (GTQ)" },
  { code: "HNL", name: "Lempira (HNL)" },
  { code: "MXN", name: "Peso Mexicano (MXN)" },
  { code: "NIO", name: "Córdoba (NIO)" },
  { code: "PAB", name: "Balboa (PAB)" },
  { code: "PEN", name: "Sol Peruano (PEN)" },
  { code: "PYG", name: "Guaraní (PYG)" },
  { code: "USD", name: "Dólar Estadounidense (USD)" },
  { code: "UYU", name: "Peso Uruguayo (UYU)" },
  { code: "VES", name: "Bolívar (VES)" },
  { code: "AUD", name: "Dólar Australiano (AUD)" },
  { code: "ZAR", name: "Rand Sudafricano (ZAR)" },
] as const;

export const COUNTRY_CURRENCY_MAP: Record<string, string> = {
  AR: "ARS",
  BO: "BOB",
  BR: "BRL",
  CL: "CLP",
  CO: "COP",
  CR: "CRC",
  CU: "CUP",
  DO: "DOP",
  EC: "USD",
  SV: "USD",
  GT: "GTQ",
  HN: "HNL",
  MX: "MXN",
  NI: "NIO",
  PA: "PAB",
  PY: "PYG",
  PE: "PEN",
  UY: "UYU",
  VE: "VES",
  US: "USD",
  AU: "AUD",
  ZA: "ZAR",
};
