export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  INVITE: "/invite/:token",
  ONBOARDING: "/onboarding",
  DASHBOARD: "/",
  FARM_DASHBOARD: "/farms/:farmId",
  ENTRADAS: "/farms/:farmId/entradas",
  ENTRADA_CREATE: "/farms/:farmId/entradas/nueva",
  MORTALIDAD: "/farms/:farmId/mortalidad",
  MORTALIDAD_CREATE: "/farms/:farmId/mortalidad/nueva",
  SETTINGS: "/settings",
  SETTINGS_TEAM: "/settings/team",
  SETTINGS_FARMS: "/settings/farms",
  ALIMENTACION: "/farms/:farmId/alimentacion",
  ALIMENTACION_CREATE: "/farms/:farmId/alimentacion/nueva",
  FOOD_STOCK: "/farms/:farmId/alimentacion/stock",
  FOOD_PURCHASE_CREATE: "/farms/:farmId/alimentacion/stock/nueva",
  CLASIFICACION: "/farms/:farmId/clasificacion",
  CLASIFICACION_CREATE: "/farms/:farmId/clasificacion/nueva",
  TRASLADOS: "/farms/:farmId/traslados",
  TRASLADO_CREATE: "/farms/:farmId/traslados/nuevo",
} as const;
